# https://dev.to/abiodunjames/why-docker-creating-a-multi-container-application-with-docker--1gpb
# https://docker-curriculum.com/#docker-compose
version: "3.5"
services:
    web: 
        build: 
            context: .
            dockerfile: ./dockerfiles/Dockerfile-node
        image: web-score-board
        container_name: web
        # Express framework default port number
        ports:
            - 3000:3000
        # The web service should depend on the database app
        depends_on:
            - database
        networks:
            - webnet
        # Override default command built in the image
        command: "node app.js"
        
    database:
        build: 
            context: .
            dockerfile: ./dockerfiles/Dockerfile-mongo
        image: database
        container_name: database
        ports:
            - 27017:27017
        networks:
            - webnet
        # Gaurantee persistent data
        volumes:
            - ./mongodb:/data/db

networks:
    webnet: 
        # https://docs.docker.com/compose/networking/
        name: webnet
        driver: bridge
        # Bridge network driver options: https://docs.docker.com/engine/reference/commandline/network_create/
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: 0.0.0.0 
            com.docker.network.bridge.enable_ip_masquerade: 'true'
            com.docker.network.bridge.enable_icc: 'true'
            com.docker.network.bridge.name: 'webnetBridge'

    
