# https://hub.docker.com/_/node/?tab=description&page=4
FROM node:10.15.1
COPY . /app
WORKDIR /app
RUN npm install
EXPOSE 3000
# https://stackoverflow.com/questions/46797348/docker-cmd-exec-form-for-multiple-command-execution?rq=1
CMD ["sh", "-c", "node initDB.js && node app.js"]
